### ISSUE TITLE
Error en el uso de los data frames

### ISSUE THREAD

**Issue by espher1987** [fhernanb/Manual-de-R#2]
Saludos, he estado leyendo tu libro. Muy interesante. Me gustaría que corrijas un error que aparece en el apartado:
**¿Cómo extraer elementos de un marco de datos?**
En este apartado mencionas que el uso de $ y [] son básicamente para extraer vectores.

Sin embargo no es así. El documento debería decir $ y [[]]. Esto es debido a que el uso de [] es para obtener un objeto del mismo tipo como el de origen. es decir:
mtcars$mpg es de clase numeric
mtcars[["mpg"]] también es de clase numeric

Mientras que:
mtcars["mpg"] es un dataframe

De nuevo gracias por tu libro.

**Comment by fhernanb** [comment]
Muchas gracias por su comentario. 

Ya mejoramos esa subsección y colocamos un ejemplo más que ayuda al lector a entender las similitudes y diferencias entre $,  [] y [[]].

Muchísimas gracias.
